#!/usr/bin/env node
/**
 * Start full stack: Supabase (via CLI) + web app (Docker).
 * Ensures Supabase CLI is used so supabase status, db reset, migrations all work.
 *
 * Usage: node scripts/stack-up.mjs
 * Or:    npm run stack:up
 */

import { execSync, spawn } from 'child_process';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

const root = join(process.cwd());
const envDockerPath = join(root, '.env.docker');

function run(cmd, opts = {}) {
  return execSync(cmd, { encoding: 'utf8', stdio: opts.silent ? 'pipe' : 'inherit', ...opts });
}

function runSupabase(args) {
  const cmd = `npx supabase ${args}`;
  return run(cmd, { cwd: root });
}

function isSupabaseRunning() {
  try {
    run('npx supabase status -o env', { cwd: root, silent: true });
    return true;
  } catch {
    return false;
  }
}

function getSupabaseEnv() {
  const out = run('npx supabase status -o env', { cwd: root, silent: true });
  const env = {};
  for (const line of out.split('\n')) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return env;
}

function writeEnvFiles(apiUrl, anonKey) {
  // For local dev (npm run dev) - app reads from apps/web/.env.local
  const webEnvPath = join(root, 'apps', 'web', '.env.local');
  const localUrl = apiUrl.replace(/127\.0\.0\.1|localhost/, 'localhost');
  const content = `# Auto-generated by scripts/stack-up.mjs (local Supabase)
NEXT_PUBLIC_SUPABASE_URL=${localUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;
  writeFileSync(webEnvPath, content);
  console.log('Wrote', webEnvPath);

  // For Docker - use host.docker.internal so container can reach Supabase on host
  const dockerUrl = apiUrl.replace(/127\.0\.0\.1|localhost/, 'host.docker.internal');
  const dockerContent = `# Auto-generated for docker compose (do not commit)
NEXT_PUBLIC_SUPABASE_URL=${dockerUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;
  writeFileSync(envDockerPath, dockerContent);
  console.log('Wrote', envDockerPath);
}

// Main
console.log('Be Electric – full stack (Supabase + web app)\n');

if (!isSupabaseRunning()) {
  console.log('Starting Supabase (this may take a minute on first run)...\n');
  runSupabase('start');
} else {
  console.log('Supabase is already running.\n');
}

const env = getSupabaseEnv();
const apiUrl = env.API_URL || env.SUPABASE_URL || 'http://localhost:54321';
const anonKey = env.ANON_KEY || env.SUPABASE_ANON_KEY;
if (!anonKey) {
  console.error('Could not get ANON_KEY from supabase status. Run: npx supabase status -o env');
  process.exit(1);
}

writeEnvFiles(apiUrl, anonKey);

console.log('\nStarting web app (Docker)...\n');
const proc = spawn('docker', ['compose', '--env-file', '.env.docker', 'up', '--build'], {
  cwd: root,
  stdio: 'inherit',
  shell: true,
});
proc.on('exit', (code) => process.exit(code ?? 0));
